[project]
name = "exploratory-data-analysis-eda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8,<3.12"

dependencies = [
    "google-generativeai",
    "numpy",
    "openpyxl",
    "pandas",
    "plotly",
    "python-dotenv",
    "requests",
    "scikit-learn",
    "scipy",
    "streamlit",
]
